name: reskolae
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.0.0
  shared_preferences: ^2.2.2
  flutter_form_builder: ^9.1.1
  flutter_svg: ^2.0.9
  dio: ^5.4.0
  lucide_icons: ^0.257.0
  flutter_local_notifications: ^16.3.0
  form_builder_validators: ^9.1.0
  introduction_screen: ^3.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
